### PR TITLE
Fixed MessageFormat  which is not working when the same argument is r…

### PR DESCRIPTION
**Pull request by sureshbabuinfo**
…epeated

### CODE REVIEW

**Comment by sureshbabuinfo** [comment]
@davidsowerby I have fixed an issue with the `MessageFormat` which does not work when the same argument is repeated in a message.

Ex: `This is a {0} pattern where the same argument is {0}`

Can you review and merge?

**Comment by davidsowerby** [comment]
Thanks for this - I am in the process of improving my release process - do you need this merged quickly?

**Comment by sureshbabuinfo** [comment]
@davidsowerby No problem. Now I have a copy of `MeesageFormat` within my project. But if you can merge this, I can remove that copy and make it as a dependency in my project which will help us a lot for moving forward. :)

**Comment by sureshbabuinfo** [comment]
@davidsowerby Thank you.

**Comment by davidsowerby** [comment]
I merged this and then had second thoughts, and unmerged it.

Your PR works for the use case you have given but breaks one of the other tests because the number of  parameters no longer matches the number of arguments.

Your use case is valid, but for the change to be properly effective, the method of comparing the number of parameters with the number of arguments would need to be more sophisticated to provide a correct response to the use of repeated arguments. Your proposal just ignores that comparison, which is why the other test fails.

My initial thoughts are that it would be easier to do the substitution and check for unused or unfulfilled arguments.

Unless I find time tomorrow, it would be a couple of weeks before I could look at working that change - or I would be happy to consider a revised PR from you

**Comment by sureshbabuinfo** [comment]
Yes. We can either do a substitution and check for the unfilled argument or find the biggest number in the `parameters` array and compare it with `arguments.length` which will not break your existing code . Which ever you prefer. Anyway I will look into this in the next couple of days and send you a PR.

**Comment by sureshbabuinfo** [comment]
Sorry I think I didn't read your comment properly. I think it is not valid to compare the number of parameters with the number of arguments because both the numbers will vary in my situation. I din't run your test case yet. I will check it and get back to you.

**Comment by davidsowerby** [comment]
It is just about maintaining backward compatibility .. currently `format ()` returns an unmodified pattern if there are different numbers of parameters / arguments.

So, to satisfy your (perfectly valid) use case, we simply need to ensure that an unmodified pattern is returned if there are insufficient arguments to fill all the parameters, allowing for repeated arguments.

I'm in a rush so I haven't thought yet about the case of unused parameters ... :-)

**Pull request merged**
